### ISSUE TITLE
Regarding the usage of uammd_pse

### ISSUE THREAD

**Issue by xiaocong0101** [RaulPPelaez/UAMMD_PSE_Python#2]
Thank you for your contribution. While reproducing the results from the paper, I would like to use the PSE plugin prepared for HOOMD-blue. HOOMD-blue was successfully compiled with GPU support, my system version is Ubuntu 20.04 with CUDA 10.2. but I encountered errors when compiling the PSE plugin:

> hoomd-dlext/PSE-master/PSEv1/Helper.cu(94): error: no operator "=" matches these operands
>             operand types are: cufftComplex = Scalar2
> /hoomd-dlext/PSE-1.1/PSEv1/Mobility.cu(87): error: identifier "scalar4_tex_t" is undefined

So, I switched to the new PSE developed for UAMMD and successfully completed the compilation and installation. However, as a beginner, I'm not very familiar with how UAMMD works. Could I ask for your advice on issues related to compiling hoomd-blue_PSE, or could you provide an example of running a simulation in UAMMD's Python interface using coordinate and parameter files from commonly used simulation software like GROMACS?

**Comment by RaulPPelaez** [comment]
Hi, I cannot provide support on hoomd, I suggest you ask in their repo.
This repo will only give you a python interface to compute hydrodynamic displacements, while UAMMD has a lot of temporal integration utilities they are not exposed to python via this repo.
You can use the functions here and either connect them with some MD engine of your choice or implement your own integration scheme.

A more fledged-out python interface for this (and many other hydrodynamic algorithms) can be found in https://github.com/stochasticHydroTools/libMobility

UAMMD-structured provides python interfaces for all integrators and hydrodynamic kernels in UAMMD, but you should ask there for support: https://github.com/PabloIbannez/UAMMD-structured
